FROM picsellia/cuda:11.8.0-cudnn8-ubuntu20.04-python3.9
LABEL authors="Tristan_COTTE"

RUN pip3 config set global.trusted-host "download.pytorch.org"

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

COPY training_image/requirements.txt .
RUN pip3 install -r requirements.txt

WORKDIR training_image/src


COPY training_image/src .

RUN mkdir -p saved_models && chmod 777 saved_models
RUN mkdir -p dataset && chmod 777 dataset
RUN chmod 777 ./